---

- name: Load routing nat iptable script on startup
  template: src="routingnatload.j2" dest="/etc/network/if-pre-up.d/routingnatload" mode="u=rwx,g=rx,o=rx"
  become: true

- name: create iptable scripts directory
  file: path="{{ routing_nat_iptables_dir }}" state=directory mode=0755
  become: true

- name: Create clear stale vms script
  template: src="clear_stale_vms.sh.j2" dest="{{ routing_nat_iptables_dir }}/{{ clear_stale_vms_script }}" mode="u=rwx,g=rx,o=rx"
  notify: Reload iptables
  become: true

- name: create iptables script for this vm
  template: src="vm_iptables_script.j2" dest="{{ routing_nat_iptables_dir }}/vm-{{ inventory_hostname }}.sh" mode="u=rwx,g=rx,o=rx"
  notify: Reload iptables
  become: true

- name: flush to allow ssh on new VM
  meta: flush_handlers
