---

- meta: flush_handlers

- name: Fire and forget a reboot action
  become: true
  shell: sleep 5; shutdown -r now "Ansible triggered a reboot"
  async: 1
  poll: 0
  changed_when: true
  ignore_errors: true

- name: Wait for an SSH connection (after 10 seconds)
  wait_for_connection:
    delay: 10
    timeout: 300
