---

docker_default_packages:
  Ubuntu:
    xenial:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      package: 17.09.0~ce-0~ubuntu
    bionic:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      package: 18.06.1~ce~3-0~ubuntu
  Debian:
    stretch:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
      package: 17.03.1~ce-0~debian-stretch
