---

- name: Find current checksum
  shell: curl "{{ os.checksum.url }}" | grep "CentOS-7-x86_64-GenericCloud-.....qcow2$" | tr -s ' ' | sort -r -t' ' -k2 | head -n 1 | cut -d ' ' -f1
  register: curled_checksum
  changed_when: false

- name: Set current_checksum var
  set_fact: current_checksum="{{ curled_checksum.stdout }}"