---

- name: Ensure required dirs are present
  become: true
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ os_file|dirname }}"

- include: "{{ os.name }}-checksum.yml"
  static: no

- name: Test if iso is already downloaded
  stat: path="{{ os_file }}" checksum_algorithm="{{ os.checksum.algo}}"
  register: iso_stat

- name: Download os iso
  get_url:
    url: "{{ os.url }}"
    dest: "{{ os_file }}"
    checksum: "{{ os.checksum.algo}}:{{ current_checksum }}"
  when: not iso_stat.stat.exists or ((not (stale_os_ok | default(false))) and iso_stat.stat.checksum != current_checksum)
  become: true