---

- hosts: vms
  roles:
    - role: virtu/dhcp
      tags: virtu/dhcp
      delegate_to: "{{ groups['host'] | first }}"
    - role: virtu/nat-redirect
      tags: virtu/nat-redirect
      delegate_to: "{{ groups['host'] | first }}"

- hosts: vms
  serial: 1
  pre_tasks:
      - name: check if VM exists
        become: true
        delegate_to: "{{ groups['host'] | first }}"
        shell: virsh list --name --all | grep '^{{ inventory_hostname }}$'
        register: vm_check_result
        changed_when: false
        failed_when: false
  roles:
    - role: virtu/vm/create
      tags: virtu/vm/create
      when: vm_check_result.rc == 1
      delegate_to: "{{ groups['host'] | first }}"
