---

- hosts: vms
  serial: 1
  roles:
    - role: virtu/vm/erase
      tags: virtu/vm/erase
      delegate_to: "{{ groups['host'] | first }}"

- hosts: vms
  serial: 1
  tasks:
    - name: Get network info from host
      delegate_to: "{{ groups['host'] | first }}"
      setup:
        gather_subset: network

    - name: SSH forget old vm (standard port)
      delegate_to: localhost
      command: ssh-keygen -R {{ hostvars[inventory_hostname]['ansible_host']|default(inventory_hostname) }}
      register: result
      changed_when: result.stderr.find("not found in") == -1
      ignore_errors: true
      when: ansible_port is not defined

    - name: SSH forget old vm (non standard port)
      delegate_to: localhost
      command: ssh-keygen -R [{{ hostvars[inventory_hostname]['ansible_host']|default(inventory_hostname) }}]:{{ ansible_port }}
      register: result
      changed_when: result.stderr.find("not found in") == -1
      ignore_errors: true
      when: ansible_port is defined
