---

- hosts: vms
  serial: 1
  roles:
    - role: virtu/vm/erase
      tags: virtu/vm/erase
      delegate_to: "{{ groups['host'] | first }}"

- hosts: vms
  serial: 1
  tasks:
    - name: Get network info from host
      delegate_to: "{{ groups['host'] | first }}"
      setup:
        gather_subset: network

    - name: SSH forget old vm
      local_action: shell ssh-keygen -R [{{ hostvars[inventory_hostname]['ansible_host']|default(ansible_default_ipv4.address) }}]:{{ ansible_port }}
      register: result
      changed_when: result.stderr.find("not found in") == -1
