---
- hosts: vm
  gather_facts: False
  tasks:
    - name: Ensure python 2 is installed
      raw: sudo apt-get -y install python
      when: os.name == "ubuntu16_cloudimg"
      register: result
      changed_when: result.stdout.find("python is already the newest version") == -1

- hosts: vm
  roles:
    - role: base_setup
    - role: security
