---

- hosts: vms
  roles:
    - role: virtu/nat-redirect
      tags: virtu/nat-redirect
      delegate_to: "{{ groups['host'] | first }}"

- hosts: vms
  gather_facts: true
  roles:
    - role: virtu/vm/firewall
      tags: virtu/vm/firewall
