---

- name: Reload iptables
  shell: sh "{{ init_script }}"
  notify: Restart fail2ban
  when: not reboot
  become: true
  async: 0
  poll: 0

- name: Restart fail2ban
  service: name=fail2ban state=restarted
  become: true


- name: Reboot for first initialisation
  shell: reboot
  become: true
  async: 0
  poll: 0
  when: reboot
  notify: Waiting for reboot
  ignore_errors: true

- name: Waiting for reboot
  local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_port }} state=started delay=10
  when: reboot