---

- name: Install required packages
  become: true
  apt:
    name: apt-transport-https
    state: present

- name: Install signing key
  become: true
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Install Docker repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    update_cache: true

- name: Install Docker
  become: true
  apt:
    name:
      - "docker-ce=5:{{ docker_version }}~3-0~{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}"
    state: present

- name: Install docker-py
  become: true
  apt:
    name: python3-docker
    state: present
