---

- name: Gather facts
  setup:
    gather_subset: min

- name: Enable overlay driver
  become: true
  modprobe:
    name: overlay
    state: present

- name: Persist overlay driver
  become: true
  lineinfile:
    line: overlay
    dest: /etc/modules-load.d/ansible-managed.conf
    create: true
    state: present
    insertafter: EOF

- name: Use relevant package manager
  include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: Start/Enable Docker engine
  become: true
  service:
    name: docker
    state: started
    enabled: true

- name: Install Docker configuration
  become: true
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker
