---

- name: Install tools
  become: true
  apt:
    name:
      - libvirt-clients
      - libvirt-daemon-system
      - virtinst
      - qemu-kvm
      - qemu-utils
      - dosfstools
      - mtools
      - genisoimage
    state: present
