---

- name: Load security iptable script on startup
  template: src="securityload.j2" dest="/etc/network/if-pre-up.d/securityload" mode="u=rwx,g=rx,o=rx"
  become: true

- name: create security iptables script
  template: src="security_iptables_script.sh.j2" dest="{{ security_iptables_script }}" mode="u=rwx,g=rx,o=rx"
  notify: Reload iptables
  become: true