---

- name: insert/update vmbr2 configuration
  blockinfile:
    path: /etc/network/interfaces
    backup: yes
    block: |
      auto vmbr2
      iface vmbr2 inet static
          address 192.168.0.254
          netmask 255.255.255.0
          bridge_ports none
          bridge_stp off
          bridge_fd 0
          post-up echo 1 > /proc/sys/net/ipv4/ip_forward
          post-up iptables -t nat -A POSTROUTING -s '192.168.0.0/24' -o vmbr0 -j MASQUERADE
          post-down iptables -t nat -D POSTROUTING -s '192.168.0.0/24' -o vmbr0 -j MASQUERADE
  become: true
  notify: restart network