---

- name: Test if VM already exist
  shell: qm status {{ vmid }} | grep -v "Configuration file .* does not exist"
  register: vm_already_exist_test
  changed_when: false
  ignore_errors: true
  become: true

- set_fact:
    vm_already_exist: "{{ vm_already_exist_test.rc == 0 }}"

- name: Test if iso is already downloaded
  stat: path="{{ iso_location }}/{{ os.iso }}"
  when: not vm_already_exist
  register: iso_stat

- name: Download os iso
  get_url:
    url: "{{ os.url }}"
    dest: "{{ iso_location }}"
    checksum: "sha1:{{ os.sha1 }}"
  when: not vm_already_exist and (not iso_stat.stat.exists or iso_stat.stat.checksum != os.sha1)
  become: true

- name: create vm
  shell: pvesh create "/nodes/{{ kvm_node }}/qemu" -vmid "{{ vmid }}" -balloon "{{ balloon }}" -memory "{{ memory }}" -sockets "{{ sockets }}" -cores "{{ cores }}" -net0 virtio,bridge=vmbr2 "-virtio0=local:{{ disk_size_go }},format=qcow2" -ide2 "local:iso/{{ os.iso }},media=cdrom"
  when: not vm_already_exist
  become: yes

- name: start vm
  shell: qm start "{{ vmid }}"
  register: result
  failed_when: result.rc != 0 and not ('already running' in result.stderr)
  changed_when: result.rc == 0
  become: yes