---

- name: start vm
  shell: qm start "{{ vmid }}"
  register: result
  failed_when: result.rc != 0 and not ('already running' in result.stderr)
  changed_when: result.rc == 0
  become: yes

#- name: smoketest vm started
#  uri:
#   url: "http://{{ public_ip }}:{{ port_redirect_prefix }}80/"
#   status_code: 200
#  register: result
#  until: result.status == 200
#  retries: 60
#  delay: 1
#  delegate_to: localhost
