---

vm_images_dir: "{{ vms_storage_dir }}/{{ inventory_hostname }}"
vm_seeds_dir: "{{ vm_images_dir }}/seeds"
vm_seeds_user_data: "{{ vm_seeds_dir }}/user-data"
vm_seeds_meta_data: "{{ vm_seeds_dir }}/meta-data"
vm_seeds_image_name: "{{ vm_images_dir }}/{{ inventory_hostname }}-cidata.iso"
os_file: "{{ vms_storage_dir }}/iso/{{ os.iso }}"
vm_system_disk_image: "{{ vm_images_dir }}/{{ inventory_hostname }}-root.qcow2"
vm_data_disk_image: "{{ vm_images_dir }}/{{ inventory_hostname }}-data.qcow2"
