---

- name: install base packages
  package: name="{{ item }}" state=latest
  with_items: "{{ base_packages }}"
  become: true

- name: install EPEL repo
  package: name=epel-release state=latest
  become: true
  when: ansible_distribution == 'CentOS'