---

nat_redirect_tcp:
### BBRIGHT ###
  5022:
    vm: bbright
    port: 22
  5080:
    vm: bbright
    port: 80
  5443:
    vm: bbright
    port: 443
### BFIVEN ###
  10022:
    vm: bfiven
    port: 22
  10080:
    vm: bfiven
    port: 80
  10443:
    vm: bfiven
    port: 443
### BGARBAGE ###
  15022:
    vm: bgarbage
    port: 22
  15080:
    vm: bgarbage
    port: 80
  15443:
    vm: bgarbage
    port: 443

vm_storage_base_dir: /data/virtu
