---

nat_redirect:
#  448:            #Exposed port
#    vm: hostname  #Concerned vm
#    port: 1448    #VM redirected port
#    [protos: [tcp, udp]]  #Protocol (default: [tcp])
### ROUTER ###
  25:
    vm: bgarbage
    port: 25
  80:
    vm: bibibox
    port: 80
  143:
    vm: bibibox
    port: 143
  443:
    vm: bibibox
    port: 443
  587:
    vm: bibibox
    port: 587
  993:
    vm: bibibox
    port: 993
  4190:
    vm: bibibox
    port: 4190
### BBRIGHT ###
  5022:
    vm: bbright
    port: 22
  5080:
    vm: bbright
    port: 80
  5443:
    vm: bbright
    port: 443
### BFIVEN ###
  10022:
    vm: bfiven
    port: 22
  # VPN
  11194:
    vm: bfiven
    port: 11194
    protos: [udp]
  10122:
    vm: bfiven
    port: 10122
  ## Jellyfin
  8920:
    vm: bfiven
    port: 443
  #Transmission
  51413:
    vm: bfiven
    port: 51413
    protos: [udp, tcp]
  10080:
    vm: bfiven
    port: 80
  10443:
    vm: bfiven
    port: 443
### BGARBAGE ###
  15022:
    vm: bgarbage
    port: 22
  15080:
    vm: bgarbage
    port: 80
  15443:
    vm: bgarbage
    port: 443
  # VPN
  500:
    vm: bgarbage
    port: 500
    protos: [udp]
  4500:
    vm: bgarbage
    port: 4500
    protos: [udp]
### BFIVEN_PP ###
#  20777:
#    vm: bfivenpp
#    port: 20777
#  20778:
#    vm: bfivenpp
#    port: 20778
  20022:
    vm: bfivenpp
    port: 22
  #VPN
  21194:
    vm: bfivenpp
    port: 21194
    protos: [udp]
  #Jellyfin
  8921:
    vm: bfivenpp
    port: 443
  #Transmission
  21413:
    vm: bfivenpp
    port: 21413
    protos: [udp, tcp]
  20122:
    vm: bfivenpp
    port: 10122
  20080:
    vm: bfivenpp
    port: 80
  20443:
    vm: bfivenpp
    port: 443

vm_storage_base_dir: /data/virtu
