---

nat_redirect_tcp:
#  448:            #Exposed port
#    vm: hostname  #Concerned vm
#    port: 1448    #VM redirected port
#    [proto: tcp]  #Protocol (default: tcp)
### ROUTER ###
  25:
    vm: router
    port: 25
  80:
    vm: router
    port: 80
  143:
    vm: router
    port: 143
  443:
    vm: router
    port: 443
  587:
    vm: router
    port: 587
  993:
    vm: router
    port: 993
  4190:
    vm: router
    port: 4190
### BBRIGHT ###
  5022:
    vm: bbright
    port: 22
  5080:
    vm: bbright
    port: 80
  5443:
    vm: bbright
    port: 443
### BFIVEN ###
  10022:
    vm: bfiven
    port: 22
  10122:
    vm: bfiven
    port: 10122
  10080:
    vm: bfiven
    port: 80
  10443:
    vm: bfiven
    port: 443
### BGARBAGE ###
  15022:
    vm: bgarbage
    port: 22
  15080:
    vm: bgarbage
    port: 80
  15443:
    vm: bgarbage
    port: 443

vm_storage_base_dir: /data/virtu
