---

- name: Install isc-dhcp-server
  become: true
  package: name=isc-dhcp-server state=present

- name: Configure dhcp interface
  become: true
  template: src=isc-dhcp-server.j2 dest="/etc/default/isc-dhcp-server"
  notify: restart isc-dhcp-server

- name: Configure dhcp conf
  become: true
  template: src=dhcpd.conf.j2 dest="/etc/dhcp/dhcpd.conf"
  notify: restart isc-dhcp-server