---

- name: Install essential packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - htop
    - vim

- name: install EPEL repo for RHEL like OSes
  become: true
  package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"
