---

- name: apt-get update
  become: true
  apt:
    update_cache: true
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Install essential packages
  become: true
  package:
    name:
    - curl
    - htop
    - vim
    state: present

- name: install EPEL repo for RHEL like OSes
  become: true
  package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"
