---

- name: Install tools
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt-bin
    - virtinst
    - qemu-kvm
    - qemu-utils
    - dosfstools
    - mtools
    - genisoimage
