---

os_force_update: false

os_images:
  ubuntu16_cloudimg:
    url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
    checksum:
      url: https://cloud-images.ubuntu.com/xenial/current/SHA1SUMS
      algo: sha1
    variant: virtio26
  centos7_cloudimg:
    url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
    checksum:
      url: https://cloud.centos.org/centos/7/images/sha256sum.txt
      algo: sha256
    variant: virtio26
