---

- name: Get network info from host
  setup:
    gather_subset: network

- name: Install isc-dhcp-server
  become: true
  run_once: true
  apt:
    name: isc-dhcp-server
    state: present

- name: Configure dhcp interface
  become: true
  run_once: true
  template:
    src: isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server
  notify: restart isc-dhcp-server

- name: Configure dhcp conf
  become: true
  run_once: true
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: restart isc-dhcp-server
