---

- name: Prepare exposed ports variable
  set_fact:
    haproxy_published_ports_formatted: |
      [
      {% for port in haproxy_published_ports %}
          "{{ port }}:{{ port }}"{{ '' if loop.last else ',' }}
      {% endfor %}
      ]

- name: Start or restart haproxy
  become: true
  docker_container:
    name: haproxy
    image: "{{ haproxy_registry }}{{ haproxy_repository }}:{{ haproxy_version }}"
    volumes:
      - /opt/docker-data/haproxy/config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /opt/docker-data/haproxy/config/certs:/etc/haproxy/certs
    published_ports: "{{ haproxy_published_ports_formatted }}"
    state: started
    recreate: "{{ docker_restart | default(false) | bool }}"
    restart_policy: unless-stopped
