---

host:
  hosts:
    cloud3b:

vms:
  hosts:
    bibibox:
      vm_ip: 192.168.0.5
      mac_address: 'c2:8f:2a:51:f0:89'
      os: ubuntu16_cloudimg
      cores: 2
      memory: 2048
      system_disk_size: 30G
      data_disk_size: 200G
    bbright:
      vm_ip: 192.168.0.10
      ansible_port: 5022
      mac_address: 'c2:8f:2a:51:f0:8a'
      os: centos7_cloudimg
      cores: 3
      memory: 4096
      system_disk_size: 30G
      data_disk_size: 800G
    bfiven:
      vm_ip: 192.168.0.11
      mac_address: 'c2:8f:2a:51:f0:8b'
      os: ubuntu20_cloudimg
      cores: 3
      memory: 4096
      system_disk_size: 30G
      data_disk_size: 800G
    bgarbage:
      vm_ip: 192.168.0.12
      ansible_port: 15022
      mac_address: 'c2:8f:2a:51:f0:8c'
      os: ubuntu20_cloudimg
      cores: 3
      memory: 4096
      system_disk_size: 30G
      data_disk_size: 800G
    bfivenpp:
      vm_ip: 192.168.0.13
      mac_address: 'c2:8f:2a:51:f0:8d'
      os: ubuntu20_cloudimg
      cores: 1
      memory: 1024
      system_disk_size: 20G
      data_disk_size: 5G
    test:
      vm_ip: 192.168.0.20
      ansible_port: 40022
      mac_address: 'c2:8f:2a:51:f0:8e'
      os: ubuntu16_cloudimg
      cores: 1
      memory: 512
      system_disk_size: 10G
      data_disk_size: 10G
